### ISSUE TITLE
Setting rank and symbol after element creation is not possible

### ISSUE THREAD

**Issue by alejandro-du** [vpusher/game-card#2]
This won't update the state correctly:

```
<game-card id="the-card" unrevealed></game-card>
<script>
    var card = document.getElementById("the-card");
    card.set("symbol", "♥");
    card.set("rank", "k");
</script>

```

**Comment by alejandro-du** [comment]
I created a [pull request](https://github.com/vpusher/game-card/pull/3) that fixes the issue. Hope you can merge it and publish a new version soon. I'd like to showcase this component in the release of Vaadin 8 :)

**Comment by vpusher** [comment]
Great ! I will check and release it asap.

**Comment by vpusher** [comment]
@alejandro-du  Released in version 1.0.3. Thanks a lot !

**Comment by alejandro-du** [comment]
Thank you for the component!

**Comment by vpusher** [comment]
@alejandro-du Don't hesitate to link your work when you are done ;)

**Comment by alejandro-du** [comment]
It's going to be featured in a short video... I'll let you know once I publish it ;)

**Comment by alejandro-du** [comment]
The video is ready: https://www.youtube.com/watch?v=aIbbS_o3eZs
And your web component is also featured here: https://vaadin.com/framework/whatsnew
Cheers!

**Comment by vpusher** [comment]
@alejandro-du Great 👍
