### ISSUE TITLE
Not working with Polymer 2.0.0-rc.2

### ISSUE THREAD

**Issue by alejandro-du** [vpusher/game-card#4]
The element doesn't work with Polymer 2.0.0-rc.2.

**Comment by vpusher** [comment]
@alejandro-du I will have a look into it.

**Comment by vpusher** [comment]
@alejandro-du fixed in [v1.0.4](/vpusher/game-card/releases/tag/v1.0.4)

**Comment by alejandro-du** [comment]
Hey thanks, but I couldn't make it work :/ Nothing happens when I click the cards.

**Comment by vpusher** [comment]
@alejandro-du Indeed, the cards are no more flippable by default. You need to add the `flippable` attribute to do that.

**Comment by alejandro-du** [comment]
I see! That's right, it works. However I cannot set the flippable attribute after creating the element.
